---
# tasks file for ssh_config

- name: Generate ssh key-pair
  community.crypto.openssh_keypair:
    path: "/home/{{ local_user }}/.ssh/test_ansible"
    type: rsa
    size: 4096
    state: present
    owner: "{{ local_user }}"
    group: "{{ local_user }}"
    force: no
    # passphrase: "{{ ssh_pass_phrase }}"
  delegate_to: localhost
  register: ssh_key_result

- name: Append public key to the host
  ansible.builtin.authorized_key:
    user: root
    state: present
    key: "{{ ssh_key_result.public_key }}"
