---
# tasks file for nginx_config
- name: Include nginx install tasks
  ansible.builtin.include_tasks: install.yaml

- name: Include nginx configuration tasks
  ansible.builtin.include_tasks: configure.yaml
